wiki/encyclopedia/urls.py
from django.urls import path, re_path

from . import views

app_name = 'wiki'
urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("search/", views.search, name="search"),
    path("random/", views.random, name="random"),
    path("<str:title>/", views.entry, name="entry"),
    path("<str:title>/edit/", views.edit, name="edit"),
]

wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('wiki/', include("encyclopedia.urls"))
]

wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/encyclopedia/views.py
from django.shortcuts import render, redirect
from django import forms
from . import util
from random import choice


class NewEntryForm(forms.Form):
    title = forms.CharField(
        label="Title",
        widget=forms.TextInput(
            attrs={
                'class': 'ml-2 px-2'
            }
        )
    )
    content = forms.CharField(
        label="",
        widget=forms.Textarea(
            attrs={
                'class': 'my-2'
            }
        )
    )


def index(request):
    entries = util.list_entries()
    return render(request, "encyclopedia/index.html", {
        "entries": entries,
    })


def create(request):
    entries = util.list_entries()
    if request.method == 'POST':
        form = NewEntryForm(request.POST)
        if form.is_valid:
            title = request.POST['title']
            content = request.POST['content']
            for entry in entries:
                if entry.upper() == title.upper():
                    return render(request, "encylopedia/add.html", {
                        "name": "Create Page",
                        "form": "Page Already Exist",
                    })
                else:
                    util.save_entry(title, content)
                    return redirect("wiki:entry", title=title)
    else:
        return render(request, "encyclopedia/add.html", {
            "name": "Create Page",
            "form": NewEntryForm(),
        })


def edit(request, title):
    entries = util.list_entries()
    content = util.get_entry(title)
    form = NewEntryForm(initial={'title': title, 'content': content})
    form.fields['title'].widget.attrs['readonly'] = True
    if request.method == 'POST':
        if form.is_valid:
            content = request.POST.get('content')
            for entry in entries:
                util.save_entry(title, content)
                return redirect("wiki:entry", title=title)
    else:
        return render(request, "encyclopedia/add.html", {
            "name": "Edit Page",
            "form": form,
        })


def entry(request, title):
    content = util.get_entry(title)
    if content == None:
        return render(request, "encyclopedia/error.html")
    else:
        return render(request, "encyclopedia/entry.html", {
            "title": title,
            "content": content,
        })


def random(request):
    entries = util.list_entries()
    title = choice(entries)
    return redirect("wiki:entry", title=title)


def search(request):
    entries = util.list_entries()
    query = request.GET['q']
    if len(query) != 0:
        listEntries = []
        for entry in entries:
            if query.upper() in entry.upper():
                listEntries.append(entry)
            if query.upper() == entry.upper():
                return redirect("wiki:entry", entry=entry)
        return render(request, "encyclopedia/index.html", {
            "entries": listEntries,
        })
    else:
        return redirect(("wiki:index"))

wiki/encyclopedia/templates/encyclopedia/add.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ name }}
{% endblock %}

{% block body %}

    <form method="POST">
        {% csrf_token %}
        {{ form }}
        <input class="btn btn-primary d-block" type="submit" value="Save" />
    </form>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% load markdown_extras %}

{% block title %} 
    {{ title }}
{% endblock %}

{% block body %}

    <a href="{% url 'wiki:edit' title %}" class="text-decoration-none">Edit Page</a>

    {{ content | markdown | safe }}

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Encyclopedia
{% endblock %}

{% block body %}

<h4>Page Doesn't exists</h4>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Encyclopedia
{% endblock %}

{% block body %}

{% if request.GET.q %}
    <h1>Searched Pages...</h1>
{% else %}
    <h1>All Pages</h1>
{% endif %}

<ul>
    {% for entry in entries %}
    <li class="ml-2">
        <a href="{% url 'wiki:entry' entry %}">{{ entry }}</a>
    </li>
    {% endfor %}
</ul>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">

<head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
</head>

<body>
    <div class="row">
        <div class="sidebar col-lg-3 col-md-3">
            <h2 class="p-3">Wiki</h2>
            <form action="/wiki/search/" method="GET" class="mx-2">
                <input class="search p-2" type="text" name="q" placeholder="Search Encyclopedia" autocomplete="off" autofocus>
            </form>
            <div class="m-3">
                <a href="{% url 'wiki:index' %}">Home</a>
            </div>
            <div class="m-3">
                <a href="{% url 'wiki:create' %}">Create New Page</a>
            </div>
            <div class="m-3">
                <a href="{% url 'wiki:random' %}">Random Page</a>
            </div>
            {% block nav %}
            {% endblock %}
        </div>
        <div class="main col-lg-9 col-md-9">
            {% block body %}
            {% endblock %}
        </div>
    </div>

</body>

</html>