commerce/auctions/urls.py
from django.urls import path, re_path

from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


app_name = "commerce"
urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("create", views.create, name="create"),
    path("categories/", views.categories, name="categories"),
    re_path("category/(?:(?P<category>.+)/)?$",
            views.category, name="category"),
    path("watchlist/", views.watchlist, name="watchlist"),
    path("winner/", views.winner, name="winner"),
    path("auction/<str:title>", views.auction, name="auction"),
    path("bid/<str:title>", views.bid, name="bid"),
    path("comment/<str:title>", views.comment, name="comment"),
    path("watch/<int:id>",
         views.watch, name="watch"),
    path("delete/<int:id>", views.delete, name="delete"),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

commerce/commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

commerce/auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from datetime import datetime

CATEGORIES = [
    ('FA', 'Fashion'),
    ('TY', 'Toys'),
    ('EC', 'Electronics'),
    ('HM', 'Home'),
    ('OT', 'Others'),
]


class User(AbstractUser):
    pass


class Auction(models.Model):
    a_id = models.IntegerField(primary_key=True)
    owner = models.CharField(max_length=150)
    title = models.CharField(max_length=150)
    description = models.TextField(blank=True, null=True)
    starting_bid = models.DecimalField(decimal_places=2, max_digits=10000)
    image = models.ImageField(upload_to='images/', null=True, blank=True)
    image_url = models.URLField(max_length=200, null=True, blank=True)
    created_at = models.DateField()
    category = models.CharField(
        max_length=50, choices=CATEGORIES, default="OT")
    watch = models.BooleanField(default=False, null=True)

    def __str__(self):
        return self.title


class Bid(models.Model):
    a_id = models.ForeignKey(
        "Auction", on_delete=models.CASCADE, null=True, blank=True)
    auction_id = models.IntegerField(default=False)
    user = models.CharField(max_length=150)
    bid_amount = models.FloatField()

    def __str__(self):
        return self.user


class Comment(models.Model):
    a_id = models.OneToOneField("Auction", on_delete=models.CASCADE)
    auction_id = models.IntegerField(default=False)
    user = models.CharField(max_length=150)
    comment = models.CharField(max_length=200)

    def __str__(self):
        return self.user


class WatchList(models.Model):
    a_id = models.ForeignKey(
        "Auction", on_delete=models.CASCADE, null=True, blank=True)
    auction_id = models.IntegerField(default=False)
    user = models.CharField(max_length=150)

    def __str__(self):
        return self.user


class Winner(models.Model):
    new_owner = models.CharField(max_length=150)
    title = models.CharField(max_length=150)
    price = models.FloatField()
    image = models.ImageField(upload_to='images/', default=False)

    def __str__(self):
        return self.new_owner

commerce/auctions/forms.py
from .models import User, Auction, Bid, Comment
from django.forms import ModelForm
from django.forms.widgets import NumberInput, Select, TextInput


class AuctionForm(ModelForm):
    class Meta:
        model = Auction
        fields = [
            'title',
            'image',
            'image_url',
            'category',
            'description',
            'starting_bid',
        ]


class BidForm(ModelForm):
    class Meta:
        model = Bid
        labels = {
            'bid_amount': ''
        }
        widgets = {
            'bid_amount': NumberInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Bid Amount'
                }
            ),
        }
        fields = ['bid_amount']


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        labels = {
            'comment': ''
        }
        widgets = {
            'comment': TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Add Comment...'
                }
            ),
        }
        fields = ['comment']

commerce/auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import User, Auction, Comment, WatchList
from .forms import AuctionForm, BidForm, CommentForm
import datetime
from auctions.models import Bid, Winner
from django.db.models.aggregates import Max


def index(request):
    auctions = Auction.objects.all()
    return render(request, "auctions/index.html", {
        "auctions": auctions,
    })


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return redirect("commerce:index")
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return redirect("commerce:index")


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return redirect("commerce:index")
    else:
        return render(request, "auctions/register.html")


@login_required
def create(request):
    if request.method == "POST":
        auction = Auction.objects.filter(title=request.POST['title'])
        if not auction:
            form = AuctionForm(request.POST, request.FILES)
            if form.is_valid:
                auction = form.save(commit=False)
                auction.owner = request.user.username
                auction.created_at = datetime.date.today()
                auction.save()
                return redirect("commerce:auction", title=auction.title)
        else:
            form = AuctionForm()
            message = "Auction title already exists"
            return render(request, "auctions/create.html", {
                "form": form,
                "message": message,
            })
    form = AuctionForm()
    return render(request, "auctions/create.html", {
        "form": form,
    })


@login_required
def watch(request, id):
    if WatchList.objects.filter(auction_id=id, user=request.user.username).exists():
        watchlist = WatchList.objects.get(
            auction_id=id, user=request.user.username)
        watchlist.delete()
    w = WatchList(auction_id=id, user=request.user.username)
    w.save()
    auction = Auction.objects.get(a_id=id)
    auction.watch = not auction.watch
    auction.save()
    return redirect("commerce:auction", auction.title)


@login_required
def watchlist(request):
    watch = WatchList.objects.filter(user=request.user.username)
    auctions = Auction.objects.none()
    for w in watch:
        auctions |= (Auction.objects.filter(a_id=w.auction_id, watch=True))
    return render(request, "auctions/index.html", {
        "auctions": auctions,
        "isWatchlist": True,
    })


@login_required
def categories(request):
    return render(request, "auctions/categories.html")


@login_required
def category(request, category):
    auctions = Auction.objects.filter(category=category)
    return render(request, "auctions/index.html", {
        "auctions": auctions,
    })


def auction(request, title):
    auction = Auction.objects.get(title=title)
    bids = Bid.objects.filter(auction_id=auction.a_id)
    comments = Comment.objects.filter(auction_id=auction.a_id)
    comment_form = CommentForm()
    bid_form = BidForm()
    isOwner = False
    if auction.owner == request.user.username:
        isOwner = True
    return render(request, "auctions/auction.html", {
        "auction": auction,
        "isOwner": isOwner,
        "bid_form": bid_form,
        "bids": bids,
        "comment_form": comment_form,
        "comments": comments,
    })


@login_required
def bid(request, title):
    auction = Auction.objects.get(title=title)
    bid_form = BidForm()
    if request.method == 'POST':
        bid_form = BidForm(request.POST)
        if bid_form.is_valid:
            bid_amount = float(request.POST['bid_amount'])
            if auction.starting_bid < bid_amount:
                bid = bid_form.save(commit=False)
                bid.user = request.user.username
                bid.auction_id = auction.a_id
                auction.starting_bid = bid_amount
                auction.save()
                bid.save()
                bid_form = BidForm()
    return redirect("commerce:auction", title=title)


@login_required
def comment(request, title):
    auction = Auction.objects.get(title=title)
    comment_form = CommentForm()
    if request.method == 'POST':
        bid_form = BidForm(request.POST)
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid:
            comment = comment_form.save(commit=False)
            comment.user = request.user.username
            comment.auction_id = auction.a_id
            comment.a_id = auction
            comment.save()
            comment_form = CommentForm()
    return redirect("commerce:auction", title)


@login_required
def winner(request):
    winnings = Winner.objects.filter(new_owner=request.user.username)
    return render(request, "auctions/winner.html", {
        "winnings": winnings,
    })


@login_required
def delete(request, id):
    auction = Auction.objects.get(a_id=id)
    bids = Bid.objects.filter(auction_id=id)
    if bids:
        max_bid = Bid.objects.filter(
            auction_id=id
        ).aggregate(maxbid=Max('bid_amount'))['maxbid']
        bid = Bid.objects.get(auction_id=id, bid_amount=max_bid)
        winner = Winner()
        winner.new_owner = bid.user
        winner.title = auction.title
        winner.price = bid.bid_amount
        if auction.image:
            winner.image = auction.image
        else:
            winner.image = auction.image_url
        winner.save(force_insert=True)
    auction.delete()
    return redirect("commerce:index")

commerce/auctions/templates/auctions/auction.html
{% extends "auctions/layout.html" %}
{% load bootstrap4 %}

{% block body %}

<div class="jumbotron mx-auto col-8">
    <div class="container d-flex justify-content-between align-items-center pb-2">
        {% if user.is_authenticated %}
            {% if auction.watch %}
                <a href="{% url 'commerce:watch' auction.a_id %}" class="btn btn-dark m-1">Remove from WatchList</a>
            {% else %}
                <a href="{% url 'commerce:watch' auction.a_id %}" class="btn btn-dark m-1">Add to WatchList</a>
            {% endif %}
            {% if isOwner %}
                <a href="{% url 'commerce:delete' auction.a_id %}" class="btn btn-dark m-1">Close Auction</a>
            {% endif %}
        {% endif %}
    </div>
    <div class="container d-flex flex-column justify-content-center align-items-center pb-2">
        <h2 class="display-4 pb-2">{{auction.title}}</h2>
        {% if auction.image %}
        <img src={{ auction.image.url }} class="lead img-thumbnail" alt={{auction.title}}>
        {% else %}
        <img src={{ auction.image_url }} class="lead img-thumbnail" alt={{auction.title}}>
        {% endif %}
        <hr class="my-4">
    </div>
    <p>{{ auction.description }}</p>
    <p>Created At: {{ auction.created_at }}</p>
    <h5 class="my-2">Price: Rs. {{ auction.starting_bid }}</h5>
    {% if not isOwner %}
        <p>{{ bids.count }} bid(s) so far. Your bid is the current bid</p>
        {% if user.is_authenticated %}
            <form action="{% url 'commerce:bid' auction.title %}" method="POST">
                {% csrf_token %}
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text">Rs.</span>
                    </div>
                    {{ bid_form }}
                    <div class="input-group-append">
                        <input type="submit" class="btn btn-dark" role="button" value="Place Bid">
                    </div>
                </div>
            </form>
        {% endif %}
    {% else %}
        <p>Total Number of bid(s) {{ bids.count }}</p>
    {% endif %}
    <h5>Details</h5>
    <ul>
        <li>Listed By: {{ auction.owner }}</li>
        <li>Category: {{ auction.get_category_display }}</li>
    </ul>
    {% if user.is_authenticated %}
        <form action="{% url 'commerce:comment' auction.title %}" method="POST" class="input-group mb-3">
            {% csrf_token %}
            {{ comment_form }}
            <div class="input-group-append">
                <input type="submit" class="input-group-text" id="basic-addon2" value="Comment">
            </div>
        </form>
    {% endif %}
    <h5>Comments</h5>
    {% for comment in comments %}
    <div class="card">
        <div class="card-header">
            {{ comment.user }}
        </div>
        <div class="card-body">
            {{ comment.comment }}
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

commerce/auctions/templates/auctions/categories.html
{% extends "auctions/layout.html" %}

{% block body %}

<h2>Categories</h2>

<div class="container row mx-auto">
    <ul>
        <li>
            <a class="d-block" href="{% url 'commerce:category' 'FA' %}">Fashion</a>
        </li>
        <li>
            <a class="d-block" href="{% url 'commerce:category' 'TY' %}">Toys</a>
        </li>
        <li>
            <a class="d-block" href="{% url 'commerce:category' 'EC' %}">Electronics</a>
        </li>
        <li>
            <a class="d-block" href="{% url 'commerce:category' 'HM' %}">Home</a>
        </li>
        <li>
            <a class="d-block" href="{% url 'commerce:category' 'OT' %}">Others</a>
        </li>
    </ul>
</div>
{% endblock %}

commerce/auctions/templates/auctions/create.html
{% extends "auctions/layout.html" %}
{% load bootstrap4 %}

{% block body %}
    <h2>Create Listings</h2>

    {% if message %}
        <p>{{ message }}</p>
    {% endif %}
    <form class='container px-5' method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button class='btn btn-dark' type='submit'>Save</button>
    </form>

{% endblock %}

commerce/auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% block body %}

{% if isWatchlist %}
<h2>Watchlist</h2>
{% else %}
<h2>Active Listings</h2>
{% endif %}

<div class="container row mx-auto">
    {% for auction in auctions %}
    <div class="card m-2 col-4" style="width: 18rem;">
        {% if auction.image %}
        <img src={{ auction.image.url }} class="card-img-top" alt="Auction">
        {% else %}
        <img src={{ auction.image_url }} class="card-img-top" alt="Auction">
        {% endif %}
        <div class="card-body">
            <h5 class="card-title">{{ auction.title }}</h5>
            <p class="card-text">Created At: {{auction.created_at}}</p>
            <p class="card-text">Price: Rs. {{ auction.starting_bid }}</p>
            <a href="{% url 'commerce:auction' auction.title %}" class="btn btn-dark m-1">View</a>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

commerce/auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Auctions{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <h1>Auctions</h1>
        <div>
            {% if user.is_authenticated %}
                Signed in as <strong>{{ user.username }}</strong>.
            {% else %}
                Not signed in.
            {% endif %}
        </div>
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'commerce:index' %}">Active Listings</a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'commerce:categories' %}">Categories</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'commerce:create' %}">Create Listing</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'commerce:watchlist' %}">Watchlist</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'commerce:winner' %}">Winnings</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'commerce:logout' %}">Log Out</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'commerce:login' %}">Log In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'commerce:register' %}">Register</a>
                </li>
            {% endif %}
        </ul>
        <hr>
        {% block body %}
        {% endblock %}
    </body>
</html>

commerce/auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'commerce:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'commerce:register' %}">Register here.</a>

{% endblock %}

commerce/auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'commerce:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'commerce:login' %}">Log In here.</a>

{% endblock %}

commerce/auctions/templates/auctions/winner.html
{% extends "auctions/layout.html" %}

{% block body %}

<h2>Winnings</h2>

<div class="container row mx-auto">
    {% for winning in winnings %}
        <div class="card m-2 col-4" style="width: 18rem;">
            <img src={{ winning.image.url }} class="card-img-top" alt="Auction Won">
            <div class="card-body">
                <h5 class="text-center">Congratulations You Won the Auction.</h5>
                <h6 class="card-title text-center my-1">{{ winning.title }}</h6>
                <p class="card-text text-center">For Price: Rs. {{ winning.price }}</p>
            </div>
        </div>
    {% endfor %}
</div>
{% endblock %}